name: Homie
description: Home plugin for the GhostRealms network
version: 1.1.0
author: cliff
main: net.ghostrealms.homie.Homie
commands:
    sethome:
        description: Sets the user's home to their location
        usage: /sethome
    home:
        description: Teleports the user to their home
        usage: /home
    setwork:
        description: Sets the user's workplace to their location
        usage: /setwork
    work:
        description: Teleports the user to their workplace
        usage: /work
    mark:
        description: Sets the user's temporary location
        usage: /mark
    return:
        description: Teleports the user to their temporary location
        usage: /return
permissions:
    homie.home:
        description: Teleports the user home
        default: op
    homie.work:
        description: Teleports the user to work
        default: op
    homie.return:
        description: Teleports the user to their temporary location
        default: op
    homie.sethome:
        description: Sets the users home to their current location
        default: op
    homie.setwork:
            description: Sets the users work to their current location
            default: op
    homie.mark:
            description: Sets the users temporary location to their current location
            default: op